tomaspinho/rtl8821ce

os_dep/linux/os_intfs.c
I'm getting errors building with 4.19 kernel from ubuntu kernel-ppa:
```
CC [M]  /var/lib/dkms/rtl8821ce/1.0.0/build/os_dep/linux/ioctl_linux.o
/var/lib/dkms/rtl8821ce/1.0.0/build/os_dep/linux/os_intfs.c:1325:22: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
.ndo_select_queue = rtw_select_queue,
^~~~~~~~~~~~~~~~
```
This change is based on solution reported [here](https://github.com/pvaret/rtl8192cu-fixes/issues/86#issuecomment-220650603)
=> Fix build for 4.19.0-041900rc4-generic from ubuntu kernel-ppa

os_dep/linux/rtw_android.c
Maintain compatibility with pre and post 5.0.0
Breaking change: https://github.com/torvalds/linux/commit/96d4f267e40f9509e8a66e2b39e8b95655617693
Relates to issue #21
=> Fix compilation against Linux 5.0.0

os_dep/osdep_service.c
replace get_ds() with KERNEL_DS
=> Fix compilation for Linux 5.1

README.md
Corrected Arch Linux installation command and changed Ubuntu/Debian header installation to module-assistant method.
=> README.md: corrected installation instructions

os_dep/linux/rtw_android.c
Pass the mandatory type parameter to `access_ok()` on pre-5.0 kernels,
in this case `VERIFY_READ` for reading memory.
Signed-off-by: Rafael Kitover <rkitover@gmail.com>
=> support pre-5.0 access_ok() API

os_dep/linux/rtw_cfgvendor.c
These are not correct, and are intentionally cirmcumventing changes
introduced in torvalds/linux@901bb98, but are good as a quick fix
Do not merge. Here for visibility only
=> Fixes for Linux 5.3

include/hal_ic_cfg.h
Fixes issue #34
DFS (as client, not as AP) is supported by the Windows driver, and it seems to be implemented in this driver too (i.e it notifies the upper cfg80211 layer that "Initiate Radiation" isn't allowed on these channels, and handles the frequency switch announcements sent by the AP), it was just disabled.
With this I'm able to connect to routers on 5Ghz channels up to 140.
If you wonder what DFS is:
> 5 GHz
> The 802.11 standard defines 23 20MHz wide channels in the 5 GHz spectrum. Each channel is spaced 20MHz apart and separated into three Unlicensed National Information Infrastructure (UNII) bands. Wireless devices specified as 802.11a/n/ac are capable of operating within these bands. In the United States, UNII-1 (5.150 to 5.250 GHz) containing channels 36, 40, 44, and 48 and …
=> Enable CONFIG_DFS, to support 5Ghz bands only allowed with DFS

Makefile, README.md
Debug logging is filling up logs with unnecessary information. Since a lot of people seem to be using this driver in production, I'd rather have this be disabled. Developers and people reporting issues can Recompile with the appropriate flag set.
This resolves #78 and #73
=> Disable Debug in production

core/rtw_mlme_ext.c, hal/hal_halmac.c, hal/hal_intf.c, hal/halmac/halmac_88xx/halmac_mimo_88xx.c, os_dep/linux/ioctl_cfg80211.c
=>  fallthrough is now a reserved keyword, use __fallthrough__

Makefile
Stops make complaining on in-tree compile:
drivers/net/wireless/rtl8821ce/Makefile:24: extraneous text after 'ifeq' directive
=> Remove extra bracket on srctree conditional

README.md
Do not recommend an AUR helper, as they go in and out of support all the time(not to mention that yaourt specifically is insecure and unsupported), rather link to the wiki page of AUR which contains manual build instructions.
Base Arch Linux install does not come with a compiler toolchain.
Also changed instances of "ArchLinux" into "Arch Linux".
Fixed typos.
=> Don't recommend an AUR helper for Arch

core/rtw_mlme.c
The kernel panics mentioned in #77 occur when the driver is trying to construct an RSN Information Element to send back to the access point, which is done by restructuring the existing IE that has been received previously. If the driver receives a PKMID though ioctl, which is supposed to be included in the IE, but the original IE did not contain a PMKID field, a null pointer dereference occurs.
This can be fixed in various ways:
- We can check for a null pointer beforehand and abort in this case to prevent the panic.
- We can write into the position where the PMKID is supposed to be. (According to what I gathered from the code, this can not cause any memory corruption, since the IE struct is always allocated for the maximum length, which is not reached if it does not contain a PMKID).
- …
=> Add a simple check to prevent kernel panics from nullptr dereferences

core/rtw_btcoex.c, core/rtw_ieee80211.c, core/rtw_wlan_util.c, os_dep/linux/os_intfs.c, os_dep/osdep_service.c
There was runtime problems caused due to lack of get_fs function. I fixed it.
=> Fixed kernel 5.10.0 problems mentioned  in 9fd63b7fe849f5fa8019c897d1642ce4f34bf3f7

os_dep/linux/rtw_proc.c, os_dep/osdep_service.c
They renamed a few functions in linux 5.17 breaking the build. Tested against 5.16 and 5.17.
Closes #265.
=> add support for linux 5.17

os_dep/linux/pci_intf.c
This ID can be found in the Windows driver and in rtw88.
Fixes https://github.com/tomaspinho/rtl8821ce/issues/273.
=> Add PCI ID 10ec:b821 (TP-Link AC600 Archer T2E)

README.md
Added information within the readme to describe the possibility of using a Machine Owner Key (MOK) to sign the kernel object for use on systems with Secure Boot enabled. Previously, the readme only suggested users disable Secure Boot on their machines, which may not be desired by all users.
=> Documentation for using MOK to sign kernel object

README.md
- Add the correct kernel option to disable PCIe ASPM.
- Add the grubby equivalent for managing kernel options.
=> Fix incorrect kernel option and add grubby equivalent.

core/rtw_rf.c, include/hal_data.h, include/rtw_rf.h
Basically the syntax to declare a flexible array member like this `char* regd_name[0]` has become so obsolete that it's treated as a zero sized string regardless of its contents, therefore `__fortify_stlren` was crashing while trying to read the first byte.
This also reverts #332 as it's not needed anymore.
=> Fix strlen buffer overrun

include/osdep_service.h, os_dep/linux/ioctl_cfg80211.c
These changes address a driver build warning with kernel v6.4+, and allow driver compilation and operation under kernel v6.7.  Tested on Linux 6.7-rc3 on amd64 with an rtl8821ce-based Wi-Fi adapter.
=> Kernel v6.7 changes

os_dep/linux/ioctl_cfg80211.c
On recent 6.13.4 kernel build, this check was not properly applied.
It cause incompatible pointer error without that
=> fix 6.13 kernel check

README.md
Information about installing this driver under NixOS is limited; it would be advisable to include it in the documentation, as a manual installation of the driver will not work due to the nature of the operating system.
=> Add install section for NixOS in README.md
